name: C++ Build and Test

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Compile C++ Program
        run: |
          # Compile with C++17 standard
          g++ -std=c++17 *.cpp
          if [ $? -ne 0 ]; then
            echo "Compilation failed"
            exit 1
          fi

      - name: Run tests and count failures
        run: |
          # Initialize counters
          total_tests=0
          failed_tests=0
          
          # Run all 6 test suites
          for i in {1..6}; do
            echo "Running test suite $i"
            ./test_p2.sh $i
            
            # Get the number of tests run and passed from the output
            test_output=$(./test_p2.sh $i)
            tests_run=$(echo "$test_output" | grep -o "Passed [0-9]* tests out of [0-9]*" | awk '{print $5}')
            tests_passed=$(echo "$test_output" | grep -o "Passed [0-9]* tests" | awk '{print $2}')
            
            # Update counters
            tests_in_suite=$tests_run
            failed_in_suite=$((tests_in_suite - tests_passed))
            
            total_tests=$((total_tests + tests_in_suite))
            failed_tests=$((failed_tests + failed_in_suite))
            
            echo "Test suite $i: $tests_passed passed out of $tests_in_suite tests"
          done
          
          # Report final counts
          echo "Total tests run: $total_tests"
          echo "Total tests failed: $failed_tests"
          
          # Fail the job if 4 or more tests failed
          if [ $failed_tests -ge 4 ]; then
            echo "Failing job: $failed_tests tests failed (threshold is 4)"
            exit 1
          else
            echo "Job passed: $failed_tests tests failed (below threshold of 4)"
          fi
